### PR TITLE
Drop row.names argument from read.csv call in addQueryTable

### PR DESCRIPTION
**Pull request by pralitp**
Not sure what it was doing there in the first place besides causing trouble.  The tests work without it (as well as it's use in gcam_diagnostics).

### CODE REVIEW

**Comment by rplzzz** [comment]
Note that we're not actually hitting this line in the test suite, which is why codecov's patch test is failing.  Not a huge deal, but it probably explains why we didn't catch this bug earlier.

**Comment by pralitp** [comment]
Yup, I realized after the fact that this was not the same function as I thought it was.  It would be pretty simple to add.  Although to really make this feature useful we would add a `...` argument to it which will get passed directly to `read.csv`.  If you think it is a good idea I'll put that in and add a test.

**Comment by rplzzz** [comment]
Sure, sounds good.  I opened an issue on the test situation, you can open an issue on the other thing or not, as you see fit.

**Comment by rplzzz** [comment]
All the new stuff looks good.  I think it's ready to merge whenever you're happy with it.

**Comment by pralitp** [comment]
Note, this closes #35 as well.

**Pull request merged**
