### PR TITLE
Quote model interface and database paths for piping to shell

### PR DESCRIPTION
**Pull request by calebbraun**
Fix issue that comes up on Windows where spaces in the file path get interpreted
as separate commands.

### CODE REVIEW

**Comment by rplzzz** [comment]
@calebbraun This looks good.  I take it that it worked on your system.  Do you feel up to adding an appveyor build to do automatic Windows tests?

**Comment by pralitp** [comment]
@calebbraun, please do not merge until verifying the tests pass.  It appears they are currently failing.  Trying to run this on my local machine also fails.

**Comment by calebbraun** [comment]
@pralitp Sorry about that. Should I go ahead and undo the changes `master` (leaving this branch)?

**Comment by rplzzz** [comment]
FYI, though, the appveyor build seems to be failing because the command line generated is too long (probably the filespecs for the jar files are longer on their install than on ours).  We _might_ be able to sidestep it by specifying the shell interpreter as powershell in the pipe command, assuming that that's a standard install for most windows systems.

**Comment by pralitp** [comment]
I've just opened #27.  Let's continue the conversation over there.

**Pull request merged**
